export const indianStatesAndUnionTerritories = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const discomReferences = [
  {
    value: "bescom",
    name: "BESCOM",
    region: "Bengaluru Urban/Rural and nearby Karnataka districts",
  },
  {
    value: "mescom",
    name: "MESCOM",
    region: "Mangaluru, Udupi, Shivamogga, Chikkamagaluru region",
  },
  {
    value: "hescom",
    name: "HESCOM",
    region: "Hubballi-Dharwad, Belagavi, Gadag, Haveri region",
  },
  {
    value: "gescom",
    name: "GESCOM",
    region: "Kalaburagi, Bidar, Raichur, Yadgir region",
  },
  {
    value: "cesc-mysuru",
    name: "CESC Mysuru",
    region: "Mysuru, Mandya, Hassan, Chamarajanagar region",
  },
  {
    value: "msedcl",
    name: "MSEDCL",
    region: "Most of Maharashtra outside some city/private license areas",
  },
  {
    value: "best",
    name: "BEST",
    region: "South Mumbai island city areas",
  },
  {
    value: "adani-mumbai",
    name: "Adani Electricity Mumbai",
    region: "Mumbai suburban distribution areas",
  },
  {
    value: "tata-power-mumbai",
    name: "Tata Power Mumbai",
    region: "Mumbai license areas depending on connection",
  },
  {
    value: "tangedco",
    name: "TANGEDCO / TNEB",
    region: "Tamil Nadu domestic consumers",
  },
  {
    value: "tsspdcl",
    name: "TGSPDCL / TSSPDCL",
    region: "Hyderabad and southern Telangana",
  },
  {
    value: "tsnpdcl",
    name: "TGNPDCL / TSNPDCL",
    region: "Northern Telangana districts",
  },
  {
    value: "brpl",
    name: "BSES Rajdhani",
    region: "South and West Delhi",
  },
  {
    value: "bypl",
    name: "BSES Yamuna",
    region: "East and Central Delhi",
  },
  {
    value: "tpddl",
    name: "Tata Power-DDL",
    region: "North and Northwest Delhi",
  },
  {
    value: "uhbvn",
    name: "UHBVN",
    region: "North Haryana",
  },
  {
    value: "dhbvn",
    name: "DHBVN",
    region: "South Haryana including Gurugram/Faridabad areas",
  },
  {
    value: "pspcl",
    name: "PSPCL",
    region: "Punjab",
  },
  {
    value: "jvvnl",
    name: "JVVNL",
    region: "Jaipur and parts of Rajasthan",
  },
  {
    value: "avvnl",
    name: "AVVNL",
    region: "Ajmer and parts of Rajasthan",
  },
  {
    value: "jdvvnl",
    name: "JdVVNL",
    region: "Jodhpur and western Rajasthan",
  },
  {
    value: "custom",
    name: "My Discom is not listed",
    region: "Use this for manual tariff setup in a later version",
  },
] as const;

export const languageOptions = [
  "English",
  "Hinglish",
  "Hindi",
  "Kannada",
  "Marathi",
  "Tamil",
  "Telugu",
  "Malayalam",
  "Gujarati",
  "Bengali",
  "Punjabi",
  "Odia",
] as const;

export const billingCycleOptions = [
  "1st of every month",
  "5th of every month",
  "10th of every month",
  "15th of every month",
  "20th of every month",
  "25th of every month",
  "Custom date",
] as const;

export const suggestedDiscomsByState: Record<string, string[]> = {
  "Andhra Pradesh": ["APSPDCL", "APEPDCL"],
  "Arunachal Pradesh": ["Department of Power Arunachal Pradesh"],
  Assam: ["APDCL"],
  Bihar: ["NBPDCL", "SBPDCL"],
  Chhattisgarh: ["CSPDCL"],
  Goa: ["Goa Electricity Department"],
  Gujarat: ["Torrent Power", "UGVCL", "MGVCL", "PGVCL", "DGVCL"],
  Haryana: ["UHBVN", "DHBVN"],
  "Himachal Pradesh": ["HPSEBL"],
  Jharkhand: ["JBVNL"],
  Karnataka: ["BESCOM", "MESCOM", "HESCOM", "GESCOM", "CESC Mysuru"],
  Kerala: ["KSEB"],
  "Madhya Pradesh": ["MPMKVVCL", "MPPKVVCL", "MPPKVVCL Indore"],
  Maharashtra: ["MSEDCL", "BEST", "Adani Electricity Mumbai", "Tata Power Mumbai"],
  Manipur: ["MSPDCL"],
  Meghalaya: ["MePDCL"],
  Mizoram: ["Power & Electricity Department Mizoram"],
  Nagaland: ["Department of Power Nagaland"],
  Odisha: ["TP Central Odisha", "TP Northern Odisha", "TP Western Odisha", "TP Southern Odisha"],
  Punjab: ["PSPCL"],
  Rajasthan: ["JVVNL", "AVVNL", "JdVVNL"],
  Sikkim: ["Energy & Power Department Sikkim"],
  "Tamil Nadu": ["TANGEDCO / TNEB"],
  Telangana: ["TGSPDCL / TSSPDCL", "TGNPDCL / TSNPDCL"],
  Tripura: ["TSECL"],
  "Uttar Pradesh": ["UPPCL", "MVVNL", "PVVNL", "DVVNL", "PuVVNL", "KESCO"],
  Uttarakhand: ["UPCL"],
  "West Bengal": ["WBSEDCL", "CESC Kolkata"],
  "Andaman and Nicobar Islands": ["Electricity Department Andaman and Nicobar"],
  Chandigarh: ["Electricity Wing Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["DNHDD Power Distribution Corporation"],
  Delhi: ["BSES Rajdhani", "BSES Yamuna", "Tata Power-DDL"],
  "Jammu and Kashmir": ["JPDCL", "KPDCL"],
  Ladakh: ["Ladakh Power Development Department"],
  Lakshadweep: ["Lakshadweep Electricity Department"],
  Puducherry: ["Electricity Department Puducherry"],
};
